[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.psram = enabled
board_build.arduino.memory_type = qio_opi

lib_deps =
    links2004/WebSockets@^2.4.1
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit SSD1306@^2.5.7
    adafruit/Adafruit GFX Library@^1.11.9

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
